routes/web.php
<?php

use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('users', UserController::class);
Route::resource('posts', PostController::class);
Route::resource('login', UserController::class);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Home.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Home extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Home;
use Illuminate\Http\Request;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        $posts = (new Post())->all();
        return view('post/index', compact('posts'));
    }

    public function create()
    {
        return view('post\add_post');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $title = $data['title'];
        $slug = $data['slug'];
        $description = $data['description'];
        $content = $data['content'];
        $thumbnail = $data['thumbnail'];
        $user_id = $data['user_id'];

        $posts = new Post();
        $posts->title = $title;
        $posts->slug = $slug;
        $posts->description = $description;
        $posts->content = $content;
        $posts->thumbnail = $thumbnail;
        $posts->user_id = $user_id;
        $posts->save();

        return redirect() ->back() ->with('success','Thêm thành công');
    }

    public function edit($id)
    {
        $posts = Post::where('id',$id)->first();
        return view('post\edit_post', compact('posts'));
    }

    public function update(Request $request ,$id)
    {
        $post = Post::find($id);
        $post->update($request->all());
        return redirect() ->back() ->with('success','Sửa thành công');
    }

    public function destroy($id)
    {
//        Post::find($id)->delete();
        return redirect() ->back() ->with('success','Xóa thành công');
    }

    public function show($id)
    {
//        Post::find($id)->delete();
//        return redirect() ->back() ->with('success','Xóa thành công');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $users = (new User())->all();
        return view('index', compact('users'));
    }

    public function create()
    {
        return view('add-user');
    }

    public function store(Request $request)
    {
        $name = $request->name;
        $email = $request->email;
        $password = $request->password;

        $users = new User();
        $users->name = $name;
        $users->email = $email;
        $users->password = $password;
        $users->save();

        return redirect() ->back() ->with('success','Thêm users thành công');
    }

    public function edit($id)
    {
        $users = User::where('id',$id)->first();
        return view('edit', compact('users'));
    }

    public function update($id, Request $request)
    {
        $name = $request->name;
        $email = $request->email;
        $password = $request->password;

        User::where('id','=',$id)->update([
            'name'=>$name,
            'email'=>$email,
            'password'=>$password,
        ]);
        return redirect() ->back() ->with('success','Update users thành công');
    }

    public function destroy($id)
    {
//        User::find($id)->delete();
//        return redirect() ->back() ->with('success','Xóa users thành công');
    }

    public function show($id)
    {
        User::where('id',$id)->delete();
        return redirect() ->back() ->with('success','Xóa users thành công');
    }

}

resources/views/Add-User.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADD-User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
    <div class="container" style="margin-top: 20px">
        <div class="row">
            <div class="col-md-12">
                <h2>Thêm Users</h2>
                @if(Session::has('success'))
                    <div class="alert alert-success" role="alert">
                        {{Session::get('success')}}
                    </div>
                @endif
                <form method="post" action="{{route('users.store')}}">
                    @csrf
                    <div class="md-3">
                        <label class="form-lebel">Họ Tên</label>
                        <input type="text" class="form-control" name="name" placeholder="Enter name">
                    </div>
                    <div class="md-3">
                        <label class="form-lebel">Email</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter email">
                    </div>
                    <div class="md-3">
                        <label class="form-lebel">Password</label>
                        <input type="password" class="form-control" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Thêm mới</button>
                    <a href="{{route('users.index')}}" class="btn btn-danger">Thoát</a>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

resources/views/Edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADD-User</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
    <div class="container" style="margin-top: 20px">
        <div class="row">
            <div class="col-md-12">
                <h2>Sửa Users</h2>
                @if(Session::has('success'))
                    <div class="alert alert-success" role="alert">
                        {{Session::get('success')}}
                    </div>
                @endif
                <form method="POST" action="{{route('users.update', $users)}}">
                    @csrf
                    @method("PUT")
                    <input type="hidden" name="id" value="{{$users->id}}">
                    <div class="md-3">
                        <label class="form-lebel">Họ Tên</label>
                        <input type="text" class="form-control" name="name" placeholder="Enter name" value="{{$users->name}}">
                    </div>
                    <div class="md-3">
                        <label class="form-lebel">Email</label>
                        <input type="email" class="form-control" name="email" placeholder="Enter email" value="{{$users->email}}">
                    </div>
                    <div class="md-3">
                        <label class="form-lebel">Password</label>
                        <input type="password" class="form-control" name="password" value="{{$users->password}}">
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{{route('users.index')}}" class="btn btn-danger">Thoát</a>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Xin chào') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Danh sách Users</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
    <div class="container" style="margin-top: 20px">
        <div class="row">
            <div class="col-md-12">
                <h2>Danh sách Users</h2>
                <div style="margin-left: 86%">
                    <a href="{{route('users.create')}}" class="btn btn-primary">Thêm mới</a>
                </div>
                @if(Session::has('success'))
                    <div class="alert alert-success" role="alert">
                        {{Session::get('success')}}
                    </div>
                @endif
                <table class="table">
                    <thead><tr>
                        <th>STT</th>
                        <th>Họ tên</th>
                        <th>Email</th>
                        <th>Password</th>
                        <th>Action</th>
                    </tr></thead>
                    <tbody>
                    @php
                    $i = 1;
                    @endphp
                        @foreach($users as $user)
                            <tr>
                                <td>{{$i++}}</td>
                                <th>{{$user->name}}</th>
                                <th>{{$user->email}}</th>
                                <th>{{$user->password}}</th>
                                <th><a href="{{route('users.edit',$user)}}" class="btn btn-primary">Sửa</a> |
{{--                                    <form class="btn btn-danger" method="post" action="{{ route('users.destroy', $user) }}">--}}
{{--                                        @method('delete')--}}
{{--                                        @csrf--}}
{{--                                        <div class="form-row">--}}
{{--                                            Xóa--}}
{{--                                        </div>--}}
{{--                                    </form>--}}
                                    <a href="{{route('users.destroy',$user)}}" class="btn btn-danger">Xóa</a></th>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/css/app.scss', 'resources/js/app.js'])

    <!-- Style -->
    <link href="{{asset('assets/css/sb-admin-2.min.css')}}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/post/add_post.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADD_post</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
<div class="container" style="margin-top: 20px">
    <div class="row">
        <div class="col-md-12">
            <h2>Thêm bài viết</h2>
            @if(Session::has('success'))
                <div class="alert alert-success" role="alert">
                    {{Session::get('success')}}
                </div>
            @endif
            <form method="post" action="{{route('posts.store')}}">
                @csrf
                <div class="md-3">
                    <label class="form-lebel">Title</label>
                    <input type="text" class="form-control" name="title">
                </div>
                <div class="md-3">
                    <label class="form-lebel">Slug</label>
                    <input type="text" class="form-control" name="slug">
                </div>
                <div class="md-3">
                    <label class="form-lebel">Description</label>
                    <input style="height: 150px" class="form-control" name="description">
                </div>
                <div class="md-3">
                    <label class="form-lebel">Content</label>
                    <input type="text" class="form-control" name="content">
                </div>
                <div class="md-3">
                    <label class="form-lebel">image</label>
                    <input type="file" class="form-control" name="thumbnail">
                </div>
                <div class="md-3">
                    <label class="form-lebel">User_id</label>
                    <input type="text" class="form-control" name="user_id">
                </div>
                <button type="submit" class="btn btn-primary">Thêm mới</button>
                <a href="{{route('posts.index')}}" class="btn btn-danger">Thoát</a>
            </form>
        </div>
    </div>
</div>

</body>
</html>

resources/views/post/edit_post.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit_post</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
<div class="container" style="margin-top: 20px">
    <div class="row">
        <div class="col-md-12">
            <h2>Sửa bài viết</h2>
            @if(Session::has('success'))
                <div class="alert alert-success" role="alert">
                    {{Session::get('success')}}
                </div>
            @endif
            <form method="POST" action="{{route('posts.update', $posts)}}">
                @csrf
                @method("PUT")
{{--                <input type="hidden" name="id" value="{{$posts->id}}">--}}
                <div class="md-3">
                    <label class="form-lebel">Title</label>
                    <input type="text" class="form-control" name="title" value="{{$posts->title ?? ''}}">
                </div>
                <div class="md-3">
                    <label class="form-lebel">Slug</label>
                    <input type="text" class="form-control" name="slug" value="{{$posts->slug ?? ''}}">
                </div>
                <div class="md-3">
                    <label class="form-lebel">Description</label>
                    <input style="height: 150px" class="form-control" name="description" value="{{$posts->description ?? ''}}">
                </div>
                <div class="md-3">
                    <label class="form-lebel">Content</label>
                    <input type="text" class="form-control" name="content" value="{{$posts->content ?? ''}}">
                </div>
                <div class="md-3">
                    <label class="form-lebel">image</label>
                    <input type="file" class="form-control" accept="image/*" onchange="loadFile(event)" name="thumbnail" value="{{$posts->thumbnail ?? ''}}">
                    <img class="form-control" style="height: 200px; width: 200px; margin-top: 10px" id="output" />
                    <script>
                        var loadFile = function(event) {
                            var output = document.getElementById('output');
                            output.src = URL.createObjectURL(event.target.files[0]);
                            output.onload = function() {
                                URL.revokeObjectURL(output.src) // free memory
                            }
                        };
                    </script>
{{--                    <input type="file" class="form-control" name="thumbnail" value="{{$posts->thumbnail ?? ''}}">--}}
                </div>
                <div class="md-3">
                    <label class="form-lebel">User_id</label>
                    <input type="text" class="form-control" name="user_id" value="{{$posts->user_id ?? ''}}">
                </div>
                <button type="submit" class="btn btn-primary"> Sửa </button>
                <a href="{{route('posts.index')}}" class="btn btn-danger">Thoát</a>
            </form>
        </div>
    </div>
</div>

</body>
</html>

resources/views/post/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Danh sách bài viết</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body>
<div class="container" style="margin-top: 20px">
    <div class="row">
        <div class="col-md-12">
            <h2>Danh sách bài viết</h2>
            <div style="margin-left: 86%">
                <a href="{{route('posts.create')}}" class="btn btn-primary">Thêm bài viết</a>
            </div>
            @if(Session::has('success'))
                <div class="alert alert-success" role="alert">
                    {{Session::get('success')}}
                </div>
            @endif
            <table class="table">
                <thead><tr>
                    <th>STT</th>
                    <th>Title</th>
                    <th>Slug</th>
                    <th>Description</th>
                    <th>Content</th>
                    <th>Thumbnail</th>
                    <th>Name</th>
                </tr></thead>
                <tbody>
                @foreach($posts as $key => $post)
                    <tr>
                        <td>{{$key}}</td>
                        <th>{{$post->tile}}</th>
                        <th>{{$post->slug}}</th>
                        <th>{{$post->description}}</th>
                        <th>{{$post->content}}</th>
                        <th>{{$post->thumbnail}}</th>
                        <th>{{$post->user->name ?? ''}}</th>
                        <th><a href="{{route('posts.edit',$post)}}" class="btn btn-primary">Sửa</a> |
                            <form class="btn btn-danger" method="post" action="{{ route('posts.destroy', $post)}}">
                                @method('delete')
                                @csrf
                               <button type="submit">Xóa</button>
                            </form>
{{--                            <a href="{{route('posts.destroy',$post)}}" class="btn btn-danger">Xóa</a></th>--}}
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>